name: explora_utm
description: Aplicación de exploración del campus de la Universidad Tecnológica de la Mixteca.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Mapas
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Geolocalización
  geolocator: ^12.0.0

  # UI / Tipografía
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2719.3

  # Imágenes en caché
  cached_network_image: ^3.3.1

  # Utilidades
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/